# Generated by Django 3.1.5 on 2021-01-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(1, 'Select a Category'), (2, 'Reminder'), (3, 'Task'), (4, 'Assignment'), (5, 'Exam')], default=None)),
                ('title', models.CharField(max_length=200)),
                ('complete', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(default='2021-01-10')),
            ],
        ),
    ]
